"""removed restaurant column from cart table

Revision ID: 12c1f587c565
Revises: 982832d2e035
Create Date: 2026-01-10 13:09:50.953377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c1f587c565'
down_revision: Union[str, Sequence[str], None] = '982832d2e035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'price')
    op.drop_constraint(op.f('uq_user_restaurant_cart'), 'carts', type_='unique')
    op.drop_constraint(op.f('carts_restaurant_id_fkey'), 'carts', type_='foreignkey')
    op.drop_column('carts', 'restaurant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('restaurant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('carts_restaurant_id_fkey'), 'carts', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_restaurant_cart'), 'carts', ['user_id', 'restaurant_id'], postgresql_nulls_not_distinct=False)
    op.add_column('cart_items', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
