"""added updated by to all tables

Revision ID: d2d2a472284e
Revises: 7990cab8db38
Create Date: 2025-11-15 22:14:33.739416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2d2a472284e"
down_revision: Union[str, Sequence[str], None] = "7990cab8db38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("restaurants", sa.Column("created_by", sa.UUID(), nullable=True))
    op.alter_column("restaurants", "cuisine", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(
        None, "restaurants", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "restaurants", type_="foreignkey")
    op.alter_column(
        "restaurants", "cuisine", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("restaurants", "created_by")
    # ### end Alembic commands ###
